# solo me arranco en linux
import uuid
from pprint import pprint

# Import the required measurement.
import netmeasure.measurements.latency.measurements as lams

# Create a measurement.
# Note: A measurement requires an id. This id will be added to all results
# generated by this measurement instance.
latencia = lams.LatencyMeasurement(id=str(uuid.uuid4()), host='127.0.0.1')

# Run the measurement.
my_result = latencia.measure()

# Print the measurement result(s)
pprint(my_result)